/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.68
 * Generated at: 2016-02-26 09:31:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class highlightNodesGraph_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/jsp/template.jsp", Long.valueOf(1456463024000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Topology</title>\r\n");
      out.write("\r\n");
      out.write("<!-- js imports -->\r\n");
      out.write("<script type=\"text/javascript\" src='");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("'></script>\r\n");
      out.write("<script type='text/javascript' src='");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("'></script>\r\n");
      out.write("<script type='text/javascript' src='");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("'></script>\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("\tsrc='");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("'></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<h2>CoprHD Topology</h2>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"mynetwork\" class=\"imgcontainer\"></div>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar network;\r\n");
      out.write("\t\tvar allNodes;\r\n");
      out.write("\t\tvar nodes = [];\r\n");
      out.write("\t\tvar edges = [];\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar IMGS_DIR = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resources/images/';\r\n");
      out.write("\t\tvar highlightActive = false;\r\n");
      out.write("\r\n");
      out.write("\t\tvar nodesDataset = new vis.DataSet(); // these come from WorldCup2014.js\r\n");
      out.write("\t\tvar edgesDataset = new vis.DataSet(); // these come from WorldCup2014.js\r\n");
      out.write("\r\n");
      out.write("\t\tfunction getGraphData() {\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype : \"GET\",\r\n");
      out.write("\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/getGraphData\",\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tgraphData = data;\r\n");
      out.write("\t\t\t\t\tprocessGraphData();\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\t\tconsole.log(\"ERROR: \", e);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tdone : function(e) {\r\n");
      out.write("\t\t\t\t\tconsole.log(\"DONE\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction processGraphData() {\r\n");
      out.write("\t\t\tvar nodesList = graphData.nodes;\r\n");
      out.write("\t\t\tvar edgesList = graphData.edges;\r\n");
      out.write("\r\n");
      out.write("\t\t\t// Build the nodes.\r\n");
      out.write("\t\t\t// BUGFIX: need to hardcode group: 1\r\n");
      out.write("\t\t\tfor (index in nodesList) {\r\n");
      out.write("\t\t\t\tdataObj = nodesList[index];\r\n");
      out.write("\t\t\t\tnodes.push({\r\n");
      out.write("\t\t\t\t\tid : dataObj.id,\r\n");
      out.write("\t\t\t\t\tlabel : dataObj.label,\r\n");
      out.write("\t\t\t\t\tgroup : 1,\r\n");
      out.write("\t\t\t\t\ttitle : dataObj.title,\r\n");
      out.write("\t\t\t\t\timage : dataObj.image,\r\n");
      out.write("\t\t\t\t\tshape : dataObj.shape,\r\n");
      out.write("\t\t\t\t\tmeta : dataObj.meta\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tfor (index in edgesList) {\r\n");
      out.write("\t\t\t\tdataObj = edgesList[index];\r\n");
      out.write("\t\t\t\tedges.push({\r\n");
      out.write("\t\t\t\t\tfrom : dataObj.from,\r\n");
      out.write("\t\t\t\t\tto : dataObj.to,\r\n");
      out.write("\t\t\t\t\tlength : dataObj.length,\r\n");
      out.write("\t\t\t\t\tdashes : dataObj.dashes\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tredrawAll();\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction redrawAll() {\r\n");
      out.write("\t\t\tnodesDataset = new vis.DataSet(nodes); // these come from WorldCup2014.js\r\n");
      out.write("\t\t\tedgesDataset = new vis.DataSet(edges); // these come from WorldCup2014.js\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar container = document.getElementById('mynetwork');\r\n");
      out.write("\t\t\tvar options = {\r\n");
      out.write("\t\t\t\tlayout : {\r\n");
      out.write("\t\t\t\t\trandomSeed : 1\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tphysics : false,\r\n");
      out.write("\t\t\t\tinteraction : {\r\n");
      out.write("\t\t\t\t\ttooltipDelay : 0,\r\n");
      out.write("\t\t\t\t\thideEdgesOnDrag : true\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\tvar data = {\r\n");
      out.write("\t\t\t\tnodes : nodesDataset,\r\n");
      out.write("\t\t\t\tedges : edgesDataset\r\n");
      out.write("\t\t\t} // Note: data is coming from ./datasources/WorldCup2014.js\r\n");
      out.write("\r\n");
      out.write("\t\t\tnetwork = new vis.Network(container, data, options);\r\n");
      out.write("\r\n");
      out.write("\t\t\t// get a JSON object\r\n");
      out.write("\t\t\tallNodes = nodesDataset.get({\r\n");
      out.write("\t\t\t\treturnType : \"Object\"\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\tnetwork.on(\"click\", neighbourhoodHighlight);\r\n");
      out.write("\t\t\tnetwork.on(\"doubleClick\", function (params) {\r\n");
      out.write("\t\t\t\tredrawAll();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction neighbourhoodHighlight(params) {\r\n");
      out.write("\t\t\t// if something is selected:\r\n");
      out.write("\t\t\tif (params.nodes.length > 0) {\r\n");
      out.write("\t\t\t\thighlightActive = true;\r\n");
      out.write("\t\t\t\tvar i, j;\r\n");
      out.write("\t\t\t\tvar selectedNode = params.nodes[0];\r\n");
      out.write("\t\t\t\tvar degrees = 1;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t// mark all nodes as hard to read.\r\n");
      out.write("\t\t\t\tfor ( var nodeId in allNodes) {\r\n");
      out.write("\t\t\t\t\tallNodes[nodeId].color = 'rgba(200,200,200,0.5)';\r\n");
      out.write("\t\t\t\t\tvar disabledImageName = IMGS_DIR+allNodes[nodeId].meta+\"-disabled.png\"; \r\n");
      out.write("\t\t\t\t\tallNodes[nodeId].image = disabledImageName;\r\n");
      out.write("\t\t\t\t\tif (allNodes[nodeId].hiddenLabel === undefined) {\r\n");
      out.write("\t\t\t\t\t\tallNodes[nodeId].hiddenLabel = allNodes[nodeId].label;\r\n");
      out.write("\t\t\t\t\t\tallNodes[nodeId].label = undefined;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tvar connectedNodes = network.getConnectedNodes(selectedNode);\r\n");
      out.write("\t\t\t\tvar allConnectedNodes = [];\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t// all first degree nodes get their own color and their label back\r\n");
      out.write("\t\t\t\tfor (i = 0; i < connectedNodes.length; i++) {\r\n");
      out.write("\t\t\t\t\tallNodes[connectedNodes[i]].color = undefined;\r\n");
      out.write("\t\t\t\t\tvar enabledImageName = IMGS_DIR+allNodes[connectedNodes[i]].meta+\".png\";\r\n");
      out.write("\t\t\t\t\tallNodes[connectedNodes[i]].image = enabledImageName;\r\n");
      out.write("\t\t\t\t\tif (allNodes[connectedNodes[i]].hiddenLabel !== undefined) {\r\n");
      out.write("\t\t\t\t\t\tallNodes[connectedNodes[i]].label = allNodes[connectedNodes[i]].hiddenLabel;\r\n");
      out.write("\t\t\t\t\t\tallNodes[connectedNodes[i]].hiddenLabel = undefined;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t// the main node gets its own color and its label back.\r\n");
      out.write("\t\t\t\tvar enabledImageName = IMGS_DIR+allNodes[selectedNode].meta+\".png\";\r\n");
      out.write("\t\t\t\tallNodes[selectedNode].color = undefined;\r\n");
      out.write("\t\t\t\tallNodes[selectedNode].image = enabledImageName;\r\n");
      out.write("\t\t\t\tif (allNodes[selectedNode].hiddenLabel !== undefined) {\r\n");
      out.write("\t\t\t\t\tallNodes[selectedNode].label = allNodes[selectedNode].hiddenLabel;\r\n");
      out.write("\t\t\t\t\tallNodes[selectedNode].hiddenLabel = undefined;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t} else if (highlightActive === true) {\r\n");
      out.write("\t\t\t\t// reset all nodes\r\n");
      out.write("\t\t\t\tfor ( var nodeId in allNodes) {\r\n");
      out.write("\t\t\t\t\tallNodes[nodeId].color = undefined;\r\n");
      out.write("\t\t\t\t\tvar enabledImageName = IMGS_DIR+allNodes[nodeId].meta+\".png\";\r\n");
      out.write("\t\t\t\t\tallNodes[nodeId].image = enabledImageName;\r\n");
      out.write("\t\t\t\t\tif (allNodes[nodeId].hiddenLabel !== undefined) {\r\n");
      out.write("\t\t\t\t\t\tallNodes[nodeId].label = allNodes[nodeId].hiddenLabel;\r\n");
      out.write("\t\t\t\t\t\tallNodes[nodeId].hiddenLabel = undefined;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\thighlightActive = false\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t// transform the object into an array\r\n");
      out.write("\t\t\tvar updateArray = [];\r\n");
      out.write("\t\t\tfor (nodeId in allNodes) {\r\n");
      out.write("\t\t\t\tif (allNodes.hasOwnProperty(nodeId)) {\r\n");
      out.write("\t\t\t\t\tupdateArray.push(allNodes[nodeId]);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tnodesDataset.update(updateArray);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tgetGraphData();\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/jsp/template.jsp(14,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/resources/js/jquery.js");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /WEB-INF/jsp/template.jsp(15,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/resources/js/vis.js");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f2.setParent(null);
    // /WEB-INF/jsp/template.jsp(16,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f2.setValue("/resources/js/googleAnalytics.js");
    int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
    if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f3.setParent(null);
    // /WEB-INF/jsp/template.jsp(18,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f3.setValue("/resources/css/topology.css");
    int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
    if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f4.setParent(null);
    // /WEB-INF/jsp/template.jsp(19,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f4.setValue("/resources/css/vis.css");
    int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
    if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f5.setParent(null);
    // /WEB-INF/jsp/highlightNodesGraph.jsp(5,6) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f5.setValue("/resources/js/datasources/TopologyDataset.js");
    int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
    if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
    return false;
  }
}
